# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
   # - name: setup-msbuild
    #  uses: microsoft/setup-msbuild@v1.1
    
    - name: Restore Packages
      run: |
        git submodule update --init --recursive
        nuget restore NoFuserEx/NoFuserEx.sln
    
    - name: Build solution
      run: msbuild NoFuserEx/NoFuserEx.sln -t:rebuild -property:Configuration=Release -property:AllowUnsafeBlocks=True

    - uses: actions/upload-artifact@v4
      with:
        name: NoFuserEx
        path: NoFuserEx
